#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
JIRA Configuration - 自动引导用户配置

首次使用会提示输入 URL 和 Token，保存到本地配置文件
之后自动读取配置，无需重复设置
"""
import os
import sys

CONFIG_FILE = os.path.join(os.path.dirname(__file__), '.jira_config')

def load_config():
    """从配置文件加载配置"""
    config = {}
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if '=' in line and not line.startswith('#'):
                        key, value = line.split('=', 1)
                        config[key.strip()] = value.strip()
        except:
            pass
    return config

def save_config(url, token):
    """保存配置到文件"""
    with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
        f.write(f"# JIRA Configuration\n")
        f.write(f"# Generated by config.py\n")
        f.write(f"JIRA_URL={url}\n")
        f.write(f"JIRA_TOKEN={token}\n")
    print(f"\n[OK] 配置已保存到: {CONFIG_FILE}")
    print("  如需修改，请删除该文件重新运行或手动编辑\n")

def prompt_for_config(existing_url="", existing_token=""):
    """交互式提示用户输入配置"""
    try:
        print("\n" + "="*50)
        print("[*] JIRA 配置向导")
        print("="*50)
        print("\n首次使用需要配置 JIRA 连接信息\n")
        
        # 提示 URL
        print("请输入 JIRA 地址:")
        print("  示例: https://your-company.atlassian.net")
        print("  或内网地址: https://jira.your-company.com")
        print("  或内网: https://jira.internal.company.com")
        
        if existing_url:
            print(f"\n当前已有: {existing_url} (直接回车使用)")
        
        url = input("\nJIRA URL: ").strip()
        if not url:
            if existing_url:
                url = existing_url
            else:
                print("[ERROR] URL 不能为空")
                sys.exit(1)
        
        # 移除末尾斜杠
        url = url.rstrip('/')
        
        # 提示 Token
        print("\n请输入 JIRA Personal Access Token:")
        print("  获取方式: 登录 JIRA -> 头像 -> Profile -> Personal Access Tokens -> Create token")
        
        if existing_token:
            print(f"\n当前已有: {'*' * 8}{existing_token[-4:] if len(existing_token) > 8 else '****'} (直接回车使用)")
        
        token = input("JIRA Token: ").strip()
        if not token:
            if existing_token:
                token = existing_token
            else:
                print("[ERROR] Token 不能为空")
                sys.exit(1)
        
        # 确认保存
        print(f"\n配置信息:")
        print(f"  URL:   {url}")
        print(f"  Token: {'*' * 8}{token[-4:] if len(token) > 8 else '****'}")
        
        confirm = input("\n确认保存? (y/n): ").strip().lower()
        if confirm == 'y' or confirm == '':
            save_config(url, token)
            return url, token
        else:
            print("[ERROR] 配置已取消")
            sys.exit(1)
            
    except (EOFError, IOError, OSError):
        # 非交互式环境下，提供详细的设置说明
        print("\n" + "="*50)
        print("[!] 无法启动交互式配置")
        print("="*50)
        print("\n检测到您可能不在交互式终端中。")
        print("请选择以下方式配置:\n")
        print("方法1: 设置环境变量 (推荐)")
        print("  PowerShell:")
        print("    $env:JIRA_URL='https://your-company.atlassian.net'")
        print("    $env:JIRA_TOKEN='your_token'")
        print("  Bash:")
        print("    export JIRA_URL='https://your-company.atlassian.net'")
        print("    export JIRA_TOKEN='your_token'")
        print("\n方法2: 手动创建配置文件")
        print(f"  在 scripts/config 目录下创建 {CONFIG_FILE}:")
        print("    JIRA_URL=https://your-company.atlassian.net")
        print("    JIRA_TOKEN=your_token")
        print("\n常见 JIRA 地址:")
        print("  - Atlassian Cloud: https://your-company.atlassian.net")
        print("  - 内网地址: https://jira.internal.company.com")
        print("="*50)
        sys.exit(1)

def is_interactive():
    """检查是否在交互式终端"""
    try:
        return sys.stdin.isatty() and sys.stdout.isatty()
    except:
        return False

def get_config():
    """获取配置（优先级：环境变量 > 配置文件 > 交互输入）"""
    # 1. 先检查环境变量
    env_url = os.environ.get('JIRA_URL', '')
    env_token = os.environ.get('JIRA_TOKEN', '')
    
    # 2. 再检查配置文件
    file_config = load_config()
    file_url = file_config.get('JIRA_URL', '')
    file_token = file_config.get('JIRA_TOKEN', '')
    
    # 3. 合并配置（环境变量优先）
    url = env_url or file_url
    token = env_token or file_token
    
    # 4. 如果两者都有，直接返回
    if url and token:
        return url, token
    
    # 5. 否则需要配置
    if is_interactive():
        try:
            url, token = prompt_for_config(url, token)
            return url, token
        except (EOFError, IOError, OSError):
            # 交互式失败，显示非交互式帮助
            pass
    
    # 6. 非交互模式：显示帮助信息
    print("\n" + "="*50)
    print("[!] JIRA 配置不完整")
    print("="*50)
    
    missing_url = not (env_url or file_url)
    missing_token = not (env_token or file_token)
    
    if missing_url and missing_token:
        print("\nJIRA_URL 和 JIRA_TOKEN 都未设置")
    elif missing_url:
        print("\nJIRA_TOKEN 已设置，但 JIRA_URL 缺失")
    else:
        print("\nJIRA_URL 已设置，但 JIRA_TOKEN 缺失")
    
    print("\n" + "="*50)
    print("请选择以下方式配置:")
    print("="*50)
    print("\n方法1: 环境变量 (临时)")
    print("  PowerShell: $env:JIRA_URL='...' ; $env:JIRA_TOKEN='...'")
    print("  Bash: export JIRA_URL='...' ; export JIRA_TOKEN='...'")
    print("\n方法2: 环境变量 (永久)")
    print("  PowerShell:")
    print("    [Environment]::SetEnvironmentVariable('JIRA_URL', 'url', 'User')")
    print("    [Environment]::SetEnvironmentVariable('JIRA_TOKEN', 'token', 'User')")
    print("  Bash (添加到 ~/.bashrc):")
    print("    echo \"export JIRA_URL='...'\" >> ~/.bashrc")
    print("    echo \"export JIRA_TOKEN='...'\" >> ~/.bashrc")
    print("\n方法3: 配置文件")
    print(f"  创建文件: {CONFIG_FILE}")
    print("  内容:")
    if missing_url:
        print("    JIRA_URL=https://your-company.atlassian.net")
    if missing_token:
        print("    JIRA_TOKEN=your_token_here")
    print("\n方法4: 交互式配置")
    print("  在交互式终端中运行: cd scripts && python my_tickets.py")
    print("\n" + "="*50)
    print("常见 JIRA 地址:")
    print("  - Atlassian Cloud: https://your-company.atlassian.net")
    print("  - 大众内网: https://devstack.vgc.com.cn/jira")
    print("="*50)
    sys.exit(1)

# 导出配置
JIRA_URL, JIRA_TOKEN = get_config()
